// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavouritesController from "./favourites_controller"
application.register("favourites", FavouritesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertReviewsController from "./insert_reviews_controller"
application.register("insert-reviews", InsertReviewsController)
